import gymnasium as gym
import gym_continuous_maze
import numpy as np
import matplotlib.pyplot as plt

env = gym.make('GoalContinuousMazeBlocks-10x10-v0', render_mode='rgb_array')
obs,_ = env.reset()
im = env.render()
plt.imshow(im)
obs,r,t1,t2,_ = env.step(np.array([0,1]))
im = env.render()
plt.imshow(im)
obs,r,t1,t2,_ = env.step(np.array([0,0.3]))
im = env.render()
plt.imshow(im)
plt.axis('off')
# obs,_ = env.reset()
# im = env.render()
# plt.imshow(im)
# obs,r,t1,t2,_ = env.step(np.array([1,0]))
# obs,r,t1,t2,_ = env.step(np.array([1,0]))
# obs,r,t1,t2,_ = env.step(np.array([0,1]))
# obs,r,t1,t2,_ = env.step(np.array([0,1]))
# obs,r,t1,t2,_ = env.step(np.array([0,1]))
# obs,r,t1,t2,_ = env.step(np.array([0,1]))
# obs,r,t1,t2,_ = env.step(np.array([1,0]))
# obs,r,t1,t2,_ = env.step(np.array([0,-1]))
# obs,r,t1,t2,_ = env.step(np.array([0,-1]))
# obs,r,t1,t2,_ = env.step(np.array([0,-1]))
# obs,r,t1,t2,_ = env.step(np.array([0.5,0]))
# im = env.render()
# plt.imshow(im)
# obs,r,t1,t2,_ = env.step(np.array([0,1]))
# obs,r,t1,t2,_ = env.step(np.array([0,1]))
# obs,r,t1,t2,_ = env.step(np.array([0,1]))
# obs,r,t1,t2,_ = env.step(np.array([0,1]))
# obs,r,t1,t2,_ = env.step(np.array([0,0.5]))
# im = env.render()
# plt.imshow(im)

# obs,r,t1,t2,_ = env.step(np.array([0,-0.1]))
# im = env.render()
# plt.imshow(im)
